# Generated by Django 3.2.16 on 2023-03-28 18:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='photos/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_article', models.TextField(max_length=255, null=True)),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('category', models.CharField(choices=[('TECH', 'TECH'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('PROGRAMMING', 'PROGRAMMING')], max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True)),
                ('tags', models.ManyToManyField(to='website.tag')),
            ],
        ),
    ]
