# Generated by Django 4.0.5 on 2022-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_article',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
