# Generated by Django 4.0.5 on 2022-07-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_sub_categories_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
