# Generated by Django 4.0.5 on 2022-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
