# Generated by Django 4.0.6 on 2022-07-18 22:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_post_category_alter_post_sub_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
