# Generated by Django 4.0.6 on 2022-07-18 22:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_post_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
