# Generated by Django 4.0.6 on 2022-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_post_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
